### ISSUE TITLE
Can we merge both of our libraries together?

### ISSUE THREAD

**Issue by dom96** [status-im/nim-metrics#10]
Perhaps you just missed it, but I've implemented a Prometheus library here: https://github.com/dom96/prometheus.

If you didn't miss it, is there a reason why you decided to start your own implementation?

It would be nice if we could merge our efforts together. What do you think?

**Comment by stefantalpalaru** [comment]
I have in mind a generic metrics library that supports more than Prometheus. Statsd and Graphite's Carbon would be the next targets. The user should be able to switch between protocols and push/pull strategies while using the same metric primitives.

From a quick look at your library, changing collector values doesn't seem thread-safe. Am I missing something? I stole the official Go client library's atomic operations idea for that (there's a nice trick to apply them to float64 values by treating them as int64). The rest is inspired by the newer Python client.

You're ahead when it comes to implementing default collectors. I'm just starting on those. I'll take a look at what you have.

> It would be nice if we could merge our efforts together. What do you think?

I'm all for it. Some implementation details on my end:

- What the Prometheus client lib guidelines call "Metric", I call "Collector". What they call "Sample", I call "Metric". I didn't want to mimic Go's interfaces when I had no need for them.
- There's no per-collector expensive `collect()` procedure that transforms a regular histogram into a cumulative one, like in their Python client. I just return that collector's metrics. The expensive part is when I deepcopy the register to take a snapshot of the state.
- Due to @zah's diligence, metrics collection is almost a zero-cost abstraction, when disabled. It's disabled by default.
- Because of @zah's appetite for unreadable language features, `{.global.}` vars are used in the alternative API (the one for one-off, quick and dirty collectors that the user is too lazy to declare first). That implied that any global vars used in there also need to be `{.global.}`. It got a bit ugly, but it works as expected.
- I like readability, so I avoided macros so far. Templates were unavoidable.
- I may choose a slower and simpler implementation early on, waiting for some real data on whether it needs to be optimised and uglified later.

**Comment by dom96** [comment]
> I have in mind a generic metrics library that supports more than Prometheus.

That's awesome! Maybe it would be possible to move some of the features from your current Prometheus library into mine, and then use my Prometheus library as a dependency? That way we can reduce the duplication.

> From a quick look at your library, changing collector values doesn't seem thread-safe. Am I missing something? I stole the official Go client library's atomic operations idea for that (there's a nice trick to apply them to float64 values by treating them as int64). The rest is inspired by the newer Python client.

Yeah, I intentionally didn't bother with thread-safety for now as I didn't need it in my project. Definitely something critical to implement.

> What the Prometheus client lib guidelines call "Metric", I call "Collector". What they call "Sample", I call "Metric". I didn't want to mimic Go's interfaces when I had no need for them.

For familiarity with other Prometheus clients I would prefer if we stuck to the guidelines.

> There's no per-collector expensive collect() procedure that transforms a regular histogram into a cumulative one, like in their Python client. I just return that collector's metrics. The expensive part is when I deepcopy the register to take a snapshot of the state.

If I understand correctly, since what you're calling collector is actually "metric", it's the same in my library. I have a ``collect`` method but on my collectors, which is there to allow extensibility.

> Due to @zah's diligence, metrics collection is almost a zero-cost abstraction, when disabled. It's disabled by default.

How is this achieved? From what I imagined metrics collection can be disabled completely with a simple ``-d:noPrometheus`` or similar.

> the one for one-off, quick and dirty collectors that the user is too lazy to declare first

Why do these need to be {.global.}?

> I like readability, so I avoided macros so far. Templates were unavoidable.

My library doesn't have any macros either, templates only for things like [``time``](https://github.com/dom96/prometheus/blob/master/src/prometheus/metric.nim#L315)

> I may choose a slower and simpler implementation early on, waiting for some real data on whether it needs to be optimised and uglified later.

I didn't benchmark my implementation yet, but I did benchmark my other code using it (via [``time``](https://github.com/dom96/prometheus/blob/master/src/prometheus/metric.nim#L315))

----
 
I'd really like to avoid having to have two competing implementations. I'm happy to help any way I can and even will be as flexible as possible with PRs if necessary. It already sucks that we have Chronos :/

**Comment by stefantalpalaru** [comment]
> Maybe it would be possible to move some of the features from your current Prometheus library into mine, and then use my Prometheus library as a dependency?

I don't think it makes sense to separate the supported protocols in different libraries, due to the large part of code in common. I'll know better when I implement support for a second protocol.

> For familiarity with other Prometheus clients I would prefer if we stuck to the guidelines.

Their guidelines come straight from their Go client library, where `Collector` is an interface and `counter` a struct for which that interface is implemented. That only makes sense within Go's limited OOP support. Once you have class inheritance, why have Collector, Metric and Sample classes, when you only need 2 of them?

> I have a collect method but on my collectors, which is there to allow extensibility.

I have it too, but it's not overloaded. I'll need to do that for default collectors that will get system info on demand.

> How is this achieved? From what I imagined metrics collection can be disabled completely with a simple `-d:noPrometheus` or similar.

Yes, it's controlled by compile-time defines. Besides not generating most of the metrics code when `-d:metrics` is not present, this library goes further by also avoiding the creation of global vars by outputting type aliases instead.

The idea is to be able to instrument various libraries with no extra cost for a library user that is not interested in enabling metrics.

> Why do these need to be {.global.}?

To avoid the added cost of a hash table lookup each time there's a `counter("foo_bar").inc()`. (Yes, 'tis a silly alternative API. We shall taunt it mercilessly.)

> My library doesn't have any macros either

You have one: https://github.com/dom96/prometheus/blob/e14c5aa71d9077a01f9f2f38b6e264b951eb26e7/src/prometheus/metric.nim#L91

> I'd really like to avoid having to have two competing implementations.

Competition is good for library users.

**Comment by dom96** [comment]
Okay. Fair enough. Not easy to merge these, let's keep them separate.
