### ISSUE TITLE
Thread-safety issues

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-metrics#31]
The `deepCopy` here takes a copy of all the metric values during collection:

https://github.com/status-im/nim-metrics/blob/16ec7aeccc2020666d6b7c63288153f3917222fb/metrics.nim#L301

This is made possible because of a `gcsafe` override here:

https://github.com/status-im/nim-metrics/blob/16ec7aeccc2020666d6b7c63288153f3917222fb/metrics.nim#L996

The override is invalid however - the referenced global is being accessed _during_ the deepCopy through pointers in places like: 

https://github.com/status-im/nim-metrics/blob/16ec7aeccc2020666d6b7c63288153f3917222fb/metrics.nim#L557

In particular, this means that the deepCopy values can be updated _while_ it's copying, and not necessarily atomically. 

Further, `SEQ_CST` for atomic operations is both too much and not enough: for atomic updates, `RELAXED` is enough to ensure that consistent values are written to memory - they will _eventually_ be seen by other threads - it's not enough because `deepCopy` doesn't atomically read the values it copies.

**Comment by stefantalpalaru** [comment]
https://en.cppreference.com/w/c/atomic/memory_order :

"memory_order_seq_cst  - A load operation with this memory order performs an  acquire operation, a store performs a release operation, and read-modify-write performs both an acquire operation and a release operation, plus a single total order exists in which all threads observe all modifications in the same order (see Sequentially-consistent ordering below)"

https://en.cppreference.com/w/c/atomic/memory_order#Sequentially-consistent_ordering : 

"Total sequential ordering requires a full memory fence CPU instruction on all multi-core systems. This may become a performance bottleneck since it forces the affected memory accesses to propagate to every core."

> deepCopy doesn't atomically read the values it copies

Turns out is doesn't matter, because the write is atomic over all CPU cores. There is no risk of reading garbage values.

The timing problem is not a real one, since metric setting is not synced in any way with pull-style metric collection.

So what's the thread-safety issue again?

**Comment by arnetheduck** [comment]
> but also establish a single total modification order of all atomic operations that are so tagged. 

"so tagged" - `deepCopy` isn't, thus isn't required to observe fences and on platforms which don't guarantee atomic stores (unlike x86), observing partial writes is at least theoretically possible (even if it is unlikely). You will note that the spec insists on describing "atomic operations" specifically - the kind of reading that `deepCopy` performs for individual fields is _not_ of that kind.

Using `setGauge` as an example the wider multi-threading issue is that it is a composite operation comprised of several steps that are not atomic with respect to `deepCopy` - for example, [this](https://github.com/status-im/nim-metrics/blob/16ec7aeccc2020666d6b7c63288153f3917222fb/metrics.nim#L534) will potentially add new table entries and [this](https://github.com/status-im/nim-metrics/blob/16ec7aeccc2020666d6b7c63288153f3917222fb/metrics.nim#L536) is two fields being updated separately.

**Comment by stefantalpalaru** [comment]
> "so tagged" - deepCopy isn't, thus isn't required to observe fences

You're right.

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4713.pdf - section 32.4:

`[Note:memory_order::seq_cst ensures sequential consistency only for a program that is free of data races and uses exclusively memory_order::seq_cst operations. Any use of weaker ordering will invalidate this guarantee unless extreme care is used. In particular,memory_order::seq_cst fences ensure a total order only for the fences themselves. Fences cannot, in general, be used to restore sequential consistency for atomic operations with weaker ordering specifications.— end note]`

Section 6.8.2.1:

`The execution of a program contains a data race if it contains two potentially concurrent conflicting actions, at least one of which is not atomic, and neither happens before the other, except for the special case for signal handlers described below. Any such data race results in undefined behavior.`

But also:

`[Note:Transformations that introduce a speculative read of a potentially shared memory location may not preserve the semantics of the C++program as defined in this document, since they potentially introduce a data race. However, they are typically valid in the context of an optimizing compiler that targets a specific machine with well-defined semantics for data races. They would be invalid for a hypothetical machine that is not tolerant of races or provides hardware race detection.— end note]`

---

So the question is: do we target any platform on which sequentially inconsistent read access to atomically updated memory locations would result in anything other than the old or the new value?

**Comment by arnetheduck** [comment]
the atomics are the smaller issue: the bigger issue is `deepCopy` and the label tables - these both need to be reframed for example by creating the storage locations for each potential label as part of registration, then copying the data using relaxed atomic reads.

for dynamic label creation, a lock is needed instead - `deepCopy` should be safe to use as long as it has exclusive access to the source data.

finally, when threads are _not_ used, none of this is a problem, but it bears consideration that copying the full collector at that point might not be the most efficient approach.

**Comment by arnetheduck** [comment]
Regarding ordering, one needs to decide if ordering matters or not - seq_cst _only_ matters for ordering, it has nothing to do with atomicity. For example, ordering does not matter for increasing a counter - for two competing counter increases, it doesn't matter which one is performed first - if we decide ordering does not matter (as is the case in the current code because we read each label separately, and the time/value fields separately as well), the atomics should be using relaxed operations so as not to stall all cpus needlessly - but at the same time, we need atomic operations on both reads and writes.

If a lock is used, atomics should not be used at all - the lock will take care of the fencing as well.

**Comment by stefantalpalaru** [comment]
> If a lock is used, atomics should not be used at all - the lock will take care of the atomicity and fencing as well.

But granular locking is significantly more expensive.

**Comment by stefantalpalaru** [comment]
> the bigger issue is deepCopy and the label tables

Right. Adding a new sequence of label values as a `Collector.metrics` key needs to acquire `Registry.lock`.

Shouldn't be expensive, if we only do it for new keys, because API users are encouraged to keep the total number of label values to a minimum.

**Comment by arnetheduck** [comment]
> But granular locking is significantly more expensive.

not always, in a multithreaded scenario, specially not compared to the current code - taking a lock usually one atomic acquire operation, releasing it is a release operation, most of the time - these are both cheaper than the seq_cst's being performed here - the problems start when the locks are long-lived, but they shouldn't be.

the biggest slowdown in this branch is more likely to be the memory allocation for the table and the slow deepcopy implementation that nim generally uses.

**Comment by stefantalpalaru** [comment]
Fixed by https://github.com/status-im/nim-metrics/pull/32
